import express from "express";
import signup from "./router/signup";
import categories from "./router/categories";
import signin from "./router/signin";
import conversation from "./router/conversation";
import logout from "./router/logout";
import loggedin from "./router/loggedin";
import search from "./router/search";
import vote from "./router/vote/vote";
import getvotes from "./router/vote/getvotes";
import profile from "./router/profile";
import menu from "./router/menu/menu";
const router = express.Router();
router.use(signup);
router.use(categories);
router.use(signin);
router.use(conversation);
router.use(logout);
router.use(loggedin);
router.use(search);
router.use(vote);
router.use(getvotes);
router.use(profile);
router.use(menu);
export default router;
